# AGLint config file
# Documentation: https://github.com/AdguardTeam/AGLint#configuration
root: true
allowInlineConfig: true
extends:
  - aglint:all
syntax:
  - AdblockPlus

rules:
  single-selector: ["error"]
  duplicated-hint-platforms: ["error"]
  duplicated-hints: ["error"]